name: RajeevSDKDemo
options:
  bundleIdPrefix: io.github.rajeev02
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  RajeevSDKDemo:
    type: application
    platform: iOS
    sources:
      - RajeevSDKDemo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.rajeev02.demo
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_GENERATION_MODE: GeneratedFile
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationAllButUpsideDown"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
